---
#Create Hammer directory on /root
- name: configure | create .hammer directory on user
  file: 
    path=~/.hammer
    state=directory
    mode=0755

#Copy the hammer configuration from template to the .hammer directory
- name: configure | set configuration for hammer from template
  template:
    src=hammer_config.yml.j2
    dest=~/.hammer/cli_config.yml

#Copy the manifest
- name: configure | copy manifest 
  become: yes
  copy: 
    src=satellite_manifest.zip
    dest=/root/satellite_manifest.zip

#Upload the manifest to the satellite
- name: configure | upload the manifest
  become: yes
  shell: hammer subscription upload --file  /root/satellite_manifest.zip --organization {{ organization }}

#Enabling repos on satellite
- name: configure | enable repos
  become: yes
  shell: hammer repository-set "{{ item.state }}" --organization {{ organization }} --product  "{{ item.product_name }}" --name "{{ item.name_repo }}" --releasever "{{ item.rel }}" --basearch "{{ item.architecture}}"
  with_items: "{{ repositories }}"
  ignore_errors: yes
  tags: repositories

#Get the repos ids and sync the repos
- name: configure | grab repositories uuid
  shell: hammer repository list --organization {{ organization }} | grep yum | awk '{print $1}'
  register: repos

- name: configure | sync repos on satellite
  command: hammer repository synchronize --id {{ item }} --organization {{ organization }}
  with_items: repos.stdout_lines